services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: kinga
      POSTGRES_USER: janus
      POSTGRES_DB: janus
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
